---
title: "matthew_bench"
author: "xiucheng quek"
date: "14 October 2016"
output: html_document
---

roc curve for benchmarking
```{r}
library(ggplot2)
library(plotROC)
library(dplyr)
summary_results <- list()

```



```{r}


results <- read.table('default/combined_results_family.tsv', header=T, sep='\t')
family <- read.table('rna_classes.txt')
colnames(family) <- c('family', 'sequences')
head(results)
results_with_family <- merge(results, family, by.x='sequence_a', by.y='sequences')


ggplot(results_with_family, aes(x=family, y=matthew_coefficient, fill=software)) + geom_bar( stat = "summary", fun.y = "mean", position = 'dodge') + theme(axis.text.x = element_text(angle = 90, hjust = 1)) + ggtitle('Performance Benchmark ( by RNA Class)')


cum_results <- dplyr::select(results, matthew_coefficient, software) %>% group_by(software) %>% mutate(ranking= rank(matthew_coefficient, ties.method='first'))

ggplot(cum_results, aes(x=ranking, y=matthew_coefficient, color=software, group=software)) + geom_line() + ggtitle('Performance Benchmark (cumulative)')
summary_results$mc <- dplyr::select(results, software, matthew_coefficient)  %>% group_by(software) %>% summarise_each(funs(mean))

```


## RNA Distance


```{r}

results <- read.table('default/complete.rnadist.tsv', header=T, sep='\t')
family <- read.table('rna_classes.txt')
colnames(family) <- c('family', 'sequences')
head(results)
results_with_family <- merge(results, family, by.x='sequence_a', by.y='sequences')


ggplot(results_with_family, aes(x=family, y=rnadist, fill=software)) + geom_bar( stat = "summary", fun.y = "mean", position = 'dodge') + theme(axis.text.x = element_text(angle = 90, hjust = 1)) + ggtitle(' RNADistance Performance Benchmark ( by RNA Class)')


cum_results <- dplyr::select(results, rnadist, software) %>% group_by(software) %>% mutate(ranking= rank(rnadist, ties.method='first'))

ggplot(cum_results, aes(x=ranking, y=rnadist, color=software, group=software)) + geom_line() + ggtitle('RNADistance Performance Benchmark (cumulative)')
summary_results$rnadist <- dplyr::select(results_with_family, software, rnadist)  %>% group_by(software) %>% summarise_each(funs(mean, na.rm=TRUE))


```

## SCI differences



```{r}

results <- read.table('default/completed.sci.results', sep='\t', header=T)
ref_results <- dplyr::filter(results, software=='reference')
merged_results <- merge(results, ref_results, by =c('sequence_a', 'sequence_b'))
merged_results$test_minus_ref <- merged_results$sci.x - merged_results$sci.y
merged_results <- dplyr::filter(merged_results, software.x != 'reference') 


results_with_family <- merge(merged_results, family, by.x='sequence_a', by.y='sequences')


ggplot(results_with_family, aes(x=family, y=test_minus_ref, fill=software.x)) + geom_bar( stat = "summary", fun.y = "mean", position = 'dodge') + theme(axis.text.x = element_text(angle = 90, hjust = 1)) + ggtitle(' SCI difference ( test - ref ) Performance Benchmark  ( by RNA Class)')


cum_results <- dplyr::select(merged_results, test_minus_ref, software.x) %>% group_by( software.x) %>% mutate(ranking= rank(test_minus_ref, ties.method='first'))

ggplot(cum_results, aes(x=ranking, y=test_minus_ref, color=software.x, group=software.x)) + geom_line() + ggtitle('SCI difference ( test - ref )  Performance Benchmark (cumulative)')

summary_results$sci <- dplyr::select(merged_results, test_minus_ref, software.x) %>% group_by(software.x) %>% summarise(high_sci = sum(test_minus_ref < 0 ), lower = sum(test_minus_ref > 0))


```

```{r}

do.call(cbind, summary_results)

```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
